### ISSUE TITLE
What's the license?

### ISSUE THREAD

**Issue by RQWorldblender** [meh2481/SpriteSheeter#10]
Your program has made it easy for me to make my spritesheets, but one thing I sometimes get peeved about is running into software that has been published without a license.
I may as well give a crash course on the relevant sections of US copyright laws:
- When you publish a creative work online, they are automatically considered "all rights reserved", not open source. This is approximately the same as what nearly all proprietary software is licensed under, and that technically means that everyone who gets this software, me included, is subject to the same restrictions as those of proprietary software.
- What this means is that nobody can effectively redistribute or modify this software, for example, because we don't have your explicit permission to do so. This matters more if you actually enforce your rights, and most large open source software projects take licensing seriously.
- When you attach one of the various open source software licenses to this software, you help make it clear as to what exactly we can do with this software. I've already spotted some stuff that I think can benefit from modifications (likely in a fork), but I have not yet done so out of legal caution.

**I strongly suggest you attach a license to this software. You can pick any of major open source software licenses, but some differ in being a copyleft (require others to have the same rights) or permissive license (only require attribution/credit).**

**Comment by meh2481** [comment]
Whoops my bad, I usually added WTFPL to my repos back in the day but I guess I just missed it here.

**Comment by RQWorldblender** [comment]
> Whoops my bad, I usually added WTFPL to my repos back in the day but I guess I just missed it here.

You actually meant the Unlicense, but it has almost the same effect. Finally happy that there's a license added.
I also noticed somewhere that you may be considering to transfer this repository to anyone interested. I might be considering so, but I'm not sure about if I'm ready to take over maintaining some code I haven't fully read over yet.
